############################################################
#
#    logging exceptions
#
############################################################


import logging, os

# create log file
#ONLY MAKE IF FOLDER DOES NOT EXIST
if not os.path.exists('logs'): os.mkdir('logs') #made in current directory
logging.basicConfig(filename='logs/exception.log',level=logging.ERROR)


def do_work():
    # if an exception is encountered in library code we might not know
    # what to do about it, so log error and rethrow
    raise Exception('do_work() failed')

try:
    # perform some work in library code
    do_work()
except Exception as e:
    logging.error('problem in library code ...')
    # handle the error in your code
    # because you know what you want to do about it
    print("handling exception generated by library code ...")


